walter_config:
  expense_categorization:
    num_hidden_layers: 32 # the number of hidden layers included in the expense categorization MLP
  auth:
    access_token_expiration_minutes: 15
    refresh_token_expiration_days: 7
  canaries:
    endpoint: "https://dev-api.walterai.dev"
    user_email: "canary@walterai.dev"
    user_password: "CanaryPassword1234&"
  plaid:
    client_name: "WalterAI"
    redirect_uri: "http://localhost:3000/"
    sync_transactions_webhook_url: "https://dev-api.walterai.dev/sync_transactions"