walter_config:
  artificial_intelligence:
    model_name: "Amazon: Nova Micro" # the least expensive model with sufficient input token size https://aws.amazon.com/bedrock/pricing/ (2025-02-10)
    temperature: 0.5 # controls how random or focused the model's responses to prompts are
    top_p: 0.9 # controls how many words the model considers at each step when generating text
  news_summary:
    number_of_articles: 10 # the number of the most relevant news articles to parse when generating news summaries
    lookback_window_days: 365 # the number of days to lookback when querying for recent stock news
    context: "You are a AI investment portfolio advisor that summarizes stock market news and gives readers digestible, business insights about the latest stock market movements to help them stay informed."
    prompt: "Summarize the following news article about the stock '{stock}' to give a well-written concise update of the stock and any market news relating to it but write it with headers and bodies so it looks like a formatted report. Include data where possible and only focus on the most important updates, do not simply summarize each article separately:\n{news}"
    max_length: 5000 # the max length of generated news summaries
    schedule: cron(0 5 * * ? *) # the cron schedule to invoke the create news summary and archive workflow
  newsletter:
    template: "default"
    max_length: 3000 # the max length of the generated newsletter
    schedule: cron(0 11 ? * MON-FRI *) # the cron schedule to invoke the create newsletter and send workflow