walter_config:
  expense_categorization:
    num_hidden_layers: 32 # the number of hidden layers included in the expense categorization MLP
  auth:
    access_token_expiration_minutes: 15
    refresh_token_expiration_days: 7
  canaries:
    endpoint: "https://hy447lxnrd.execute-api.us-east-1.amazonaws.com/dev"
    user_email: "canary@walterai.dev"
    user_password: "CanaryPassword1234&"