walter_config:
  model_id: "Amazon: Nova Micro"
  temperature: 0.5
  top_p: 0.9
  generate_responses: true
  newsletter_template: "default"
  send_newsletter: true
  dump_newsletter: false
  emit_metrics: true
  jwt_algorithm: "HS256"