name: Validate Infrastructure

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

env:
  TF_VERSION: '1.13.0'
  AWS_DEFAULT_REGION: ${{ vars.AWS_REGION || 'us-east-1' }}

jobs:
  terraform:
    name: 'Terraform Format and Plan'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: 'Make script executable'
        run: chmod +x scripts/plan.sh

      - name: 'Terraform Format'
        id: fmt
        run: terraform fmt -check -recursive -diff
        continue-on-error: true

      - name: 'Terraform Plan (Dev)'
        id: plan
        run: |
          ./scripts/plan.sh dev
        continue-on-error: true

      - name: 'Fail if any step failed'
        if: |
          steps.fmt.outcome == 'failure' ||
          steps.plan.outcome == 'failure'
        run: exit 1